---
title: "HW7"
author: Hallie Shi
date: March 17 2021
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import "fake data"
z <- read.table("HW7Practice.csv",header=TRUE,sep=",", stringsAsFactors=FALSE)
str(z)
summary(z)
z<- z[complete.cases(z),]

library(ggplot2)
library(MASS)

#z <- rnorm(n=3000,mean=0.2)
#z <- data.frame(1:3000,z)
# names(z) <- list("ID","myVar")

z <- z[z$Bifidobacteria>0,]# pick up the varible "Bafidobacteria"
str(z)
summary(z$Bifidobacteria)

# plot histogram of data
p1 <- ggplot(data=z,aes(x=Bifidobacteria,y=..density..))+
      geom_histogram(color="grey60",fill="cornsilk",size=0.2)
print(p1)

# Add empirical density curve
p1 <- p1 + geom_density(linetype="dotted",size=0.75)
print(p1)

# Get maximun likelihood parameters for normal
normPars <- fitdistr(z$Bifidobacteria,"normal")
print(normPars)
str(normPars) # what does this mean?
normPars$estimate["mean"]

# plot NORMAL probability density
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]
 
xval <- seq(0,max(z$Bifidobacteria,na.rm = TRUE),len=length(z$Bifidobacteria))
stat <- stat_function(aes(x=xval,y=..y..),fun=dnorm,colour="red",n=length(z$Bifidobacteria),args=list(mean=meanML,sd=sdML))
p1+stat

# plot EXPONENTICAL Probability density 
expoPars <- fitdistr(z$Bifidobacteria,"exponential")
rateML <- expoPars$estimate["rate"]
stat2 <- stat_function(aes(x=xval,y=..y..),fun=dexp,colour="darkgreen",n=length(z$Bifidobacteria),args=list(rate=rateML))
p1+stat+stat2

# Plot UNIFORM probability density
stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="blue", n = length(z$Bifidobacteria),args = list(min=min(z$Bifidobacteria),max=max(z$Bifidobacteria)))
p1 + stat + stat2 + stat3

# Plot GAMMA probability density
anyNA(z)
gammaPars <- fitdistr(z$Bifidobacteria,"gamma")
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]
stat4 <- stat_function(aes(x=xval,y=..y..),fun=dgamma,colour="brown",n=length(z$Bifidobacteria),args=list(shape=shapeML,rate=rateML))
p1 + stat+ stat2+stat3+stat4

# Plot beta Probability density.
pSpecial1 <- ggplot(data=z,aes(x=Bifidobacteria/(max(Bifidobacteria+0.1,na.rm=TRUE)), y=..density..))+
       geom_histogram(color="grey60",fill="cornsilk",size=0.2)+
       xlim(c(0,1))+
       geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$Bifidobacteria/max(z$Bifidobacteria+0.1),start=list(shape1=1,shape2=2),"beta")
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x=xval,y=..y..),fun=dbeta,colour="orchid",n=length(z$Bifidobacteria),args=list(shape1=shape1ML,shape2=shape2ML))
pSpecial1+statSpecial

```

